# Generated by Django 5.2.1 on 2025-06-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ancho (m)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Largo (m)')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Dormitorios')),
                ('bathrooms', models.PositiveSmallIntegerField(default=0, verbose_name='Baños')),
                ('parking', models.PositiveSmallIntegerField(default=0, verbose_name='Estacionamientos')),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('VISITANDO', 'En proceso de visitas'), ('VENDIDA', 'Vendida')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de venta')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='Imagen')),
                ('is_main', models.BooleanField(default=False, verbose_name='Es imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Imagen de propiedad',
                'verbose_name_plural': 'Imágenes de propiedades',
                'ordering': ['property', '-is_main'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Fecha de visita')),
                ('visit_time', models.TimeField(verbose_name='Hora de visita')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADA', 'Visita confirmada'), ('CANCELADA', 'Visita cancelada'), ('COMPLETADA', 'Visita completada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['visit_date', 'visit_time'],
            },
        ),
    ]
